#pragma once

#define PIN_MOTOR_LEFT_ENCODER_A 18
#define PIN_MOTOR_LEFT_ENCODER_B 19
#define PIN_MOTOR_LEFT_DRIVER_A 33
#define PIN_MOTOR_LEFT_DRIVER_B 25

#define PIN_USER_ENCODER_A 34
#define PIN_USER_ENCODER_B 35
#define PIN_USER_ENCODER_BUTTON 32

#define PIN_MOTOR_RIGHT_ENCODER_A 16
#define PIN_MOTOR_RIGHT_ENCODER_B 17
#define PIN_MOTOR_RIGHT_DRIVER_A 26
#define PIN_MOTOR_RIGHT_DRIVER_B 27
